// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1mfVD2NpwWRfitGlGXmM6Z3oM_Ry8Vcs',
    appId: '1:200493690867:web:5d0cab85e382edb0162c86',
    messagingSenderId: '200493690867',
    projectId: 'ecommerce-pp',
    authDomain: 'ecommerce-pp.firebaseapp.com',
    storageBucket: 'ecommerce-pp.appspot.com',
    measurementId: 'G-JM2B1DP2XS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMMtcHVjOJfWreuYRZRAVmp3J1kRxXrxE',
    appId: '1:200493690867:android:e2d5fbd892209e4b162c86',
    messagingSenderId: '200493690867',
    projectId: 'ecommerce-pp',
    storageBucket: 'ecommerce-pp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5UVLB9Vw52Uuq8VMXnxzEPL1_3lYOKnI',
    appId: '1:200493690867:ios:244bcbb727e404a0162c86',
    messagingSenderId: '200493690867',
    projectId: 'ecommerce-pp',
    storageBucket: 'ecommerce-pp.appspot.com',
    iosClientId: '200493690867-pba1tk9v5nqhge7rdljbub38a5kdgjhk.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceBloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5UVLB9Vw52Uuq8VMXnxzEPL1_3lYOKnI',
    appId: '1:200493690867:ios:70c4fc85c8b253a7162c86',
    messagingSenderId: '200493690867',
    projectId: 'ecommerce-pp',
    storageBucket: 'ecommerce-pp.appspot.com',
    iosClientId: '200493690867-be1lmbvufkivktkv9cg3m1rf6419njen.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceBloc.RunnerTests',
  );
}
